apiVersion: apps/v1 
kind: Deployment
metadata:
  name: other
spec:
  selector:
    matchLabels:
      app: other
  replicas: 1
  template:
    metadata:
      labels:
        app: other
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

