apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  action: DENY
  rules:
  - from:
    - source:
        ipBlocks: ["172.17.0.9"] 
