apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: 4e236028-ccc5-404e-99d0-3faafa17db90
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  action: DENY
  rules:
  - from:
    - source:
        ipBlocks: ["0.0.0.0" ]
