apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ad1b2639-7e8f-40e4-a41d-27e3bffc531d
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  action: DENY
  rules:
  - from:
    - source:
        ipBlocks: ["0.0.0.0/0" ]
