apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: 21ca4afc-aad1-4d9c-8eb3-6144bda0f783
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks: ["172.17.0.8"]
