apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: c9c4038c-7229-4129-97c3-df3178572004
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  action: DENY
  rules:
  - from:
    - source:
        ipBlocks: ["0.0.0.0" ]
